#!/usr/bin/env pwsh
#Requires -Version 5.1
#Requires -RunAsAdministrator

<#
.SYNOPSIS
    VaultDrift Docker Kurulum ve Çalıştırma Script'i
.DESCRIPTION
    Bu script VaultDrift'i Docker ile kurar, config oluşturur ve çalıştırır.
    Windows 10/11 + Docker Desktop gerektirir.
.EXAMPLE
    .\run.ps1
    .\run.ps1 -Port 8080 -DataDir "D:\VaultDrift\Data"
#>

[CmdletBinding()]
param(
    [int]$Port = 8080,
    [string]$DataDir = "",
    [string]$AdminUser = "admin",
    [string]$AdminEmail = "admin@localhost",
    [switch]$Force,
    [switch]$SkipBuild
)

# Renkli çıktı fonksiyonları
function Write-Header($text) {
    Write-Host ""
    Write-Host "==========================================" -ForegroundColor Cyan
    Write-Host $text -ForegroundColor Cyan
    Write-Host "==========================================" -ForegroundColor Cyan
    Write-Host ""
}

function Write-Success($text) {
    Write-Host "✓ $text" -ForegroundColor Green
}

function Write-Warning($text) {
    Write-Host "⚠ $text" -ForegroundColor Yellow
}

function Write-Error($text) {
    Write-Host "✗ $text" -ForegroundColor Red
}

function Write-Info($text) {
    Write-Host "→ $text" -ForegroundColor White
}

# Script başlangıcı
Clear-Host
Write-Header "VaultDrift Docker Kurulum"

# Dizin belirle
if ([string]::IsNullOrEmpty($DataDir)) {
    $DataDir = Join-Path $PSScriptRoot "data"
}
$DataDir = Resolve-Path $DataDir -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Path
if (-not $DataDir) { $DataDir = Join-Path $PSScriptRoot "data" }

$LogDir = Join-Path $DataDir "logs"
$StorageDir = Join-Path $DataDir "storage"

Write-Info "Veri dizini: $DataDir"
Write-Info "Port: $Port"

# Docker kontrolü
Write-Header "Docker Kontrolü"
try {
    $dockerVersion = docker version --format '{{.Server.Version}}' 2>$null
    if ($LASTEXITCODE -eq 0) {
        Write-Success "Docker çalışıyor (v$dockerVersion)"
    } else {
        throw "Docker daemon çalışmıyor"
    }
} catch {
    Write-Error "Docker bulunamadı veya çalışmıyor"
    Write-Info "Lütfen Docker Desktop'ı kurun ve başlatın:"
    Write-Info "https://www.docker.com/products/docker-desktop"
    exit 1
}

# Dizinleri oluştur
Write-Header "Dizinler Oluşturuluyor"
@($DataDir, $LogDir, $StorageDir) | ForEach-Object {
    if (-not (Test-Path $_)) {
        New-Item -ItemType Directory -Path $_ -Force | Out-Null
        Write-Success "Dizin oluşturuldu: $_"
    } else {
        Write-Info "Dizin zaten var: $_"
    }
}

# Config dosyası
Write-Header "Config Dosyası Oluşturuluyor"
$ConfigPath = Join-Path $PSScriptRoot "config.docker.yaml"

$jwtSecret = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 32 | ForEach-Object { [char]$_ })

$configContent = @"
# VaultDrift Docker Configuration
# Auto-generated by run.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

server:
  host: 0.0.0.0
  port: 8080
  base_url: http://localhost:$Port
  tls:
    enabled: false

storage:
  backend: local
  local:
    data_dir: /data/storage

database:
  path: /data/vaultdrift.db

auth:
  jwt_secret: "$jwtSecret"
  access_token_ttl: 15m
  refresh_token_ttl: 7d
  totp_enabled: true

sync:
  chunk_size_min: 262144
  chunk_size_avg: 1048576
  chunk_size_max: 4194304
  max_concurrent_transfers: 4
  websocket_enabled: true

encryption:
  enabled: true
  zero_knowledge: true

sharing:
  public_links_enabled: true
  max_expiry_days: 90
  default_expiry_days: 7

users:
  registration_enabled: false
  default_quota: 0

logging:
  level: info
  file: /data/logs/vaultdrift.log
  audit: true
  format: json
"@

$configContent | Out-File -FilePath $ConfigPath -Encoding UTF8
Write-Success "Config oluşturuldu: $ConfigPath"
Write-Info "JWT Secret: ${jwtSecret.Substring(0,8)}... (config dosyasında saklanıyor)"

# Docker Compose dosyası
Write-Header "Docker Compose Dosyası Oluşturuluyor"
$ComposePath = Join-Path $PSScriptRoot "docker-compose.run.yml"

$composeContent = @"
version: '3.8'

services:
  vaultdrift:
    build:
      context: .
      dockerfile: Dockerfile
    image: vaultdrift/vaultdrift:latest
    container_name: vaultdrift
    restart: unless-stopped
    ports:
      - "$Port:8080"
    volumes:
      - "$($DataDir):/data"
      - "$ConfigPath:/app/config.yaml:ro"
    environment:
      - VAULTDRIFT_CONFIG=/app/config.yaml
    command: ["serve", "--config", "/app/config.yaml"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
"@

$composeContent | Out-File -FilePath $ComposePath -Encoding UTF8
Write-Success "Docker Compose oluşturuldu: $ComposePath"

# Eski container'ları temizle
Write-Header "Eski Container'lar Kontrol Ediliyor"
$existingContainer = docker ps -aq -f name=^vaultdrift$ 2>$null
if ($existingContainer) {
    if ($Force) {
        Write-Warning "Eski container kaldırılıyor..."
        docker stop vaultdrift 2>$null | Out-Null
        docker rm vaultdrift 2>$null | Out-Null
        Write-Success "Eski container kaldırıldı"
    } else {
        Write-Warning "VaultDrift container'ı zaten var"
        $response = Read-Host "Kaldırıp yeniden başlatmak istiyor musunuz? (E/H)"
        if ($response -eq 'E' -or $response -eq 'e') {
            docker stop vaultdrift 2>$null | Out-Null
            docker rm vaultdrift 2>$null | Out-Null
            Write-Success "Eski container kaldırıldı"
        } else {
            Write-Info "Kurulum iptal edildi"
            exit 0
        }
    }
}

# Build ve çalıştır
Write-Header "Docker Build Başlatılıyor"
if ($SkipBuild) {
    Write-Info "Build atlanıyor (--skip-build)"
} else {
    Write-Info "Build işlemi başlıyor (bu birkaç dakika sürebilir)..."
    docker-compose -f $ComposePath build --no-cache 2>&1 | ForEach-Object {
        if ($_ -match "^(Step|Successfully|Error)") {
            Write-Host $_ -ForegroundColor Gray
        }
    }
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Build başarısız"
        exit 1
    }
    Write-Success "Build tamamlandı"
}

Write-Header "Container Başlatılıyor"
docker-compose -f $ComposePath up -d 2>&1 | Out-Null

# Sağlık kontrolü
Write-Info "Sağlık kontrolü yapılıyor (40 saniye)..."
$attempts = 0
$maxAttempts = 20
$healthy = $false

while ($attempts -lt $maxAttempts) {
    Start-Sleep -Seconds 2
    $attempts++

    $health = docker inspect --format='{{.State.Health.Status}}' vaultdrift 2>$null
    $status = docker inspect --format='{{.State.Status}}' vaultdrift 2>$null

    if ($health -eq "healthy" -or $status -eq "running") {
        $healthy = $true
        break
    }

    Write-Host -NoNewline "." -ForegroundColor Gray
}

if (-not $healthy) {
    Write-Error "Container sağlıklı başlatılamadı"
    Write-Info "Loglar kontrol ediliyor:"
    docker logs vaultdrift --tail 20
    exit 1
}

Write-Success "Container çalışıyor!"

# Admin kullanıcı oluştur
Write-Header "Admin Kullanıcı Oluşturuluyor"
$adminExists = docker exec vaultdrift test -f /data/vaultdrift.db 2>$null
if ($LASTEXITCODE -eq 0) {
    Write-Info "Veritabanı zaten var, admin kullanıcı atlanıyor"
} else {
    Write-Info "Admin kullanıcı oluşturuluyor: $AdminUser"
    Write-Warning "Aşağıdaki soruya şifre belirleyin ve girin:"
    docker exec -it vaultdrift vaultdrift-server init --admin-user $AdminUser --admin-email $AdminEmail
    if ($LASTEXITCODE -eq 0) {
        Write-Success "Admin kullanıcı oluşturuldu"
    } else {
        Write-Warning "Admin oluşturma atlandı (zaten var olabilir)"
    }
}

# Bitiş
Write-Header "VaultDrift Hazır!"
Write-Success "Web UI: http://localhost:$Port"
Write-Success "Kullanıcı: $AdminUser"
Write-Info ""
Write-Info "Komutlar:"
Write-Info "  Durum kontrolü:  docker ps"
Write-Info "  Logları izle:    docker logs -f vaultdrift"
Write-Info "  Durdur:          docker-compose -f $ComposePath down"
Write-Info "  Yeniden başlat:  docker-compose -f $ComposePath restart"
Write-Info ""
Write-Info "Verileriniz: $DataDir"
Write-Info "Config:      $ConfigPath"
Write-Info ""

# Tarayıcıyı aç (isteğe bağlı)
$response = Read-Host "Tarayıcıda açmak istiyor musunuz? (E/H)"
if ($response -eq 'E' -or $response -eq 'e') {
    Start-Process "http://localhost:$Port"
}

Write-Host "Keyifli kullanımlar! 🚀" -ForegroundColor Green
