apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultdrift
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - vaultdrift.example.com
      secretName: vaultdrift-tls
  rules:
    - host: vaultdrift.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vaultdrift
                port:
                  number: 8080
